### ISSUE TITLE
epub Doc error

### ISSUE THREAD

**Issue by CVBruce** [tabemann/zeptoforth#94]
In the file zeptoforth-1.5.4/epub/zeptoforth.epub there is the following error message.

“This page contains the following errors:error on line 1506 at column 27: Opening and ending tag mismatch: NL line 1506 and p
Below is a rendering of the page up to the first error.”

Excerpt From
zeptoforth
Travis Bemann
This material may be protected by copyright.

Error message in Apple Books v6.2

**Comment by tabemann** [comment]
Thanks for bringing this to my attention - I don't really look at the epub docs much, and I do not do so on the Mac (I had to borrow my parents' Mac to diagnose this error). It should now be fixed in the `master` and `devel` branches, and the fixed docs will appear in the next release.

**Comment by CVBruce** [comment]
Thanks!Sent from my iPhoneOn Mar 3, 2024, at 3:18 PM, tabemann ***@***.***> wrote:﻿
Closed #94 as completed.
